Creation of eq assert tests
perimetersec/fuzzlib pull request #38
Opened 2024-05-21 18:38 UTC by antks03

close #36 

@rappie

2024-05-21 18:43 UTC, aviggiano commented on test/Assert.t.sol
> +    }
This is not using concrete values

2024-05-21 18:43 UTC, aviggiano commented on test/Assert.t.sol
> +    }
Also, you're using `assertEq` from foundry

2024-05-21 18:43 UTC, aviggiano commented on test/Assert.t.sol
> +    }
As per foundry guidelines, fuzz tests should start with `testFuzz` https://book.getfoundry.sh/tutorials/best-practices?highlight=testfork#general-test-guidance

2024-05-21 18:44 UTC, aviggiano commented on test/Assert.t.sol
> +    }
Same

2024-05-21 18:44 UTC, aviggiano commented on test/Assert.t.sol
> +    function test_HelperAssert_eq_x_y_fuzz(uint256 x, uint256 y) public {
Same about `testFuzz`

2024-05-21 18:44 UTC, aviggiano commented on test/Assert.t.sol
> +    function test_HelperAssert_Ttrue() public {
typo

2024-05-21 18:44 UTC, aviggiano commented on test/Assert.t.sol
> +    function test_HelperAssert_Tfalse() public {
typo

2024-05-21 18:44 UTC, aviggiano commented on test/Assert.t.sol
> +        //vm.expectRevert();
You could also be testing for events & reverts

2024-05-23 17:17 UTC, aviggiano commented on test/Assert.t.sol
> +    function test_HelperAssert_t_true() public {
the description seems wrong
"t reverts for true", when in reality it reverts for FALSE

2024-05-23 17:24 UTC, antks03 commented on test/Assert.t.sol
> +    function test_HelperAssert_t_true() public {
wow, thank you

2024-05-23 17:29 UTC, aviggiano commented on test/Assert.t.sol
> +        t(false, "t reverts for true");
this is wrong

2024-05-27 10:48 UTC, rappie requested changes

2024-05-27 10:48 UTC, rappie commented on test/Assert.t.sol
> +    function test_HelperAssert_t_true() public {
the old tests (test_TFail and test_TSuccess) can be replaces with these new ones

2024-05-27 10:48 UTC, rappie commented on test/Assert.t.sol
> +        vm.expectRevert(PlatformTest.TestAssertFail.selector);
add vm.expectEmit

2024-05-27 10:48 UTC, rappie commented on test/Assert.t.sol
> +        emit AssertEqFail("");
shouldnt this fail? because the emitted event should have the string "eq reverts with different values"

2024-05-27 10:48 UTC, rappie commented on test/Assert.t.sol
> +        emit AssertEqFail("");
same

2024-05-30 19:09 UTC, rappie requested changes

2024-05-30 19:09 UTC, rappie commented on test/Assert.t.sol
> +        string memory reason = "t does not revert for true";
this text does not make sense for the test (testing false). i suggest we change it to some generic text that is easily copy/pasteable

2024-05-31 10:39 UTC, rappie requested changes

2024-05-31 10:39 UTC, rappie commented on test/Assert.t.sol
> +        vm.expectEmit(true, true, false, false);
this is wrong (explained in discord)

2024-05-31 10:39 UTC, rappie commented on test/Assert.t.sol
> +        emit AssertFail(reason);
reason is wrong (explained in discord)

2024-06-06 10:56 UTC, rappie approved these changes

2024-06-06 10:57 UTC, rappie commented
Looks good to me, @aviggiano could you give this a final check?

2024-06-07 11:40 UTC, merged